root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/darts ./main.go"
bin = "./tmp/darts"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["frontend", "tmp", "vendor", "testdata"]
delay = 1000
stop_on_error = true